bin/aleph2solr /data/incoming/rug01.export.gz rug01 
bin/aleph2solr /data/incoming/ser01.export.gz ser01
bin/aleph2solr /data/incoming/ejn01.export.gz ejn01
bin/aleph2solr /data/incoming/ebk01.export.gz ebk01
bin/aleph2solr /data/incoming/bkt01.export.gz bkt01
bin/aleph2solr /data/incoming/eebo1.export.gz ebo01
bin/aleph2solr /data/incoming/eebo2.export.gz ebo02
bin/aleph2solr /data/incoming/eebo3.export.gz ebo03
bin/aleph2solr /data/incoming/eebo4.export.gz ebo04
bin/aleph2solr /data/incoming/hathi.export.gz hth01
bin/aleph2solr /data/incoming/rug02.export.gz rug02 
bin/aleph2solr /data/incoming/rug03.export.gz rug03 
bin/aleph2solr /data/incoming/ath01.export.gz ath01
bin/aleph2solr /data/incoming/cgw01.export.gz cgw01
bin/aleph2solr /data/incoming/cgw02.export.gz cgw02
bin/aleph2solr /data/incoming/cgw03.export.gz cgw03
bin/aleph2solr /data/incoming/cgw04.export.gz cgw04
bin/aleph2solr /data/incoming/cgw05.export.gz cgw05
bin/aleph2solr /data/incoming/gutenberg.export.gz gtb01
bin/aleph2solr /data/incoming/dbnl.export.gz dnl01 
bin/aleph2solr /data/incoming/dbs01.export.gz dbs01 
bin/aleph2solr /data/incoming/pug01.export.gz pug01 
