bin/aleph2store /data/incoming/rug01.export.gz  rug01 /data/store/rug01.db
bin/aleph2store /data/incoming/ser01.export.gz  ser01 /data/store/ser01.db
bin/aleph2store /data/incoming/ejn01.export.gz  ejn01 /data/store/ejn01.db
bin/aleph2store /data/incoming/ebk01.export.gz  ebk01 /data/store/ebk01.db
bin/aleph2store /data/incoming/bkt01.export.gz  bkt01 /data/store/bkt01.db
bin/aleph2store /data/incoming/eebo1.export.gz  ebo01 /data/store/ebo01.db
bin/aleph2store /data/incoming/eebo2.export.gz  ebo02 /data/store/ebo02.db
bin/aleph2store /data/incoming/eebo3.export.gz  ebo03 /data/store/ebo03.db
bin/aleph2store /data/incoming/eebo4.export.gz  ebo04 /data/store/ebo04.db
bin/aleph2store /data/incoming/hathi.export.gz  hth01 /data/store/hth01.db
bin/aleph2store /data/incoming/rug02.export.gz  rug02 /data/store/rug02.db
bin/aleph2store /data/incoming/rug03.export.gz  rug03 /data/store/rug03.db
bin/aleph2store /data/incoming/ath01.export.gz  ath01 /data/store/ath01.db
bin/aleph2store /data/incoming/cgw01.export.gz  cgw01 /data/store/cgw01.db
bin/aleph2store /data/incoming/cgw02.export.gz  cgw02 /data/store/cgw02.db
bin/aleph2store /data/incoming/cgw03.export.gz  cgw03 /data/store/cgw03.db
bin/aleph2store /data/incoming/cgw04.export.gz  cgw04 /data/store/cgw04.db
bin/aleph2store /data/incoming/cgw05.export.gz  cgw05 /data/store/cgw05.db
bin/aleph2store /data/incoming/gutenberg.export.gz  gtb01 /data/store/gtb01.db
bin/aleph2store /data/incoming/dbnl.export.gz  dnl01 /data/store/dnl01.db
bin/aleph2store /data/incoming/dbs01.export.gz  dbs01 /data/store/dbs01.db
bin/aleph2store /data/incoming/pug01.export.gz  pug01 /data/store/pug01.db
