[
{
   "creator" : "lilic",
   "subjects" : "Technology and Engineering",
   "publisher_place" : "Bellingham, WA, USA",
   "keywords" : "real-time ; Cell BE ; image quality ; blur estimation ; multi-core ; wavelets",
   "id" : "828907",
   "isbn" : "9780819479280",
   "publisher" : "SPIE, the International Society for Optical Engineering",
   "doi" : "http://hdl.handle.net/10.1117/12.839501",
   "authors" : "Lukic, Nemanja ; Platisa, Ljiljana ; Pizurica, Aleksandra ; Philips, Wilfried ; Temerinac, Miodrag",
   "has_full_text" : "N",
   "conference_date" : "2010-01-17",
   "people" : "Platisa, Ljiljana (802000272646@TW07) ; Pizurica, Aleksandra (801001580450@TW07) ; Philips, Wilfried (801000739176@TW07)",
   "publication_abbreviation" : "Proc. Soc. Photo-Opt. Instrum. Eng. (SPIE)",
   "ugent_publication" : "UGENT",
   "title" : "Real-time wavelet based blur estimation on cell BE platform",
   "type" : "conference",
   "classification" : "P1",
   "pages" : "11",
   "date_created" : "2010-01-15 14:39:53",
   "issn" : "0277-786X",
   "conference_date_end" : "2010-01-21",
   "other_identifiers" : "isi:type:Proceedings Paper",
   "conference_name" : "Wavelet Applications in Industrial Processing VII",
   "issue_title" : "Wavelet applications in industrial processing VII",
   "isi_id" : "000283590300011",
   "volume" : "7535",
   "language" : "eng",
   "publication_title" : "PROCEEDINGS OF THE SOCIETY OF PHOTO-OPTICAL INSTRUMENTATION ENGINEERS (SPIE)",
   "conference_location" : "San José, CA, USA",
   "date_updated" : "2010-12-03 13:35:50",
   "publication_reference" : "Proc. Soc. Photo-Opt. Instrum. Eng. (SPIE). 2010. SPIE, the International Society for Optical Engineering. 7535",
   "departments" : "TW07",
   "publication_status" : "published",
   "abstracts" : "We propose a real-time system for blur estimation using wavelet decomposition. The system is based on an emerging multi-core microprocessor architecture (Cell Broadband Engine, Cell BE) known to outperform any available general purpose or DSP processor in the domain of real-time advanced video processing solutions. We start from a recent wavelet domain blur estimation algorithm which uses histograms of a local regularity measure called average cone ratio (ACR). This approach has shown a very good potential for assessing the level of blur in the image yet some important aspects remain to be addressed in order for the method to become a practically working one. Some of these aspects are explored in our work. Furthermore, we develop an efficient real-time implementation of the novelty metric and integrate it into a system that captures live video. The proposed system estimates blur extent and renders the results to the remote user in real-time.",
   "publication_year" : "2010"
},
{
   "creator" : "mghysbre",
   "subjects" : "Medicine and Health Sciences",
   "pages_end" : "71",
   "date_created" : "2011-02-01 14:22:51",
   "issn" : "0168-8510",
   "open_access" : "ugent",
   "issue" : "1",
   "keywords" : "REFORM ; BLOOD ; CARE ; Strategic planning ; Public health system ; HEALTH-POLICY ; SYSTEM ; LATIN-AMERICA ; Cuba ; Hospital management ; Health services organization",
   "article_type" : "original",
   "pages_start" : "64",
   "id" : "1113902",
   "doi" : "http://hdl.handle.net/10.1016/j.healthpol.2010.01.005",
   "authors" : "De Vos, Pol ; Ordunez-Garcia, Pedro ; Santos-Pena, Moises ; Van Der Stuyft, Patrick",
   "isi_id" : "000279096300010",
   "has_full_text" : "Y",
   "language" : "eng",
   "volume" : "96",
   "publication_title" : "HEALTH POLICY",
   "date_updated" : "2011-02-14 13:29:06",
   "publication_reference" : "Health Policy. 2010. 96 (1) p.64-71",
   "isi_type" : "Article",
   "departments" : "GE12",
   "publication_status" : "published",
   "people" : "De Vos, Pol (000071422312@UGent) ; Van Der Stuyft, Patrick (801001017446@GE12)",
   "publication_year" : "2010",
   "publication_abbreviation" : "Health Policy",
   "ugent_publication" : "UGENT",
   "title" : "Public hospital management in times of crisis : lessons learned from Cienfuegos, Cuba (1996-2008)",
   "type" : "journalArticle",
   "classification" : "A1"
},
{
   "creator" : "irots",
   "subjects" : "Social Sciences",
   "pages_end" : "110",
   "publisher_place" : "Mechelen",
   "date_created" : "2011-01-31 11:27:04",
   "open_access" : "ugent",
   "pages_start" : "77",
   "id" : "1112392",
   "publisher" : "Wolters Plantyn",
   "doi" : "http://hdl.handle.net/1854/LU-1112392",
   "authors" : "Rots, Isabel",
   "has_full_text" : "Y",
   "language" : "dut",
   "volume" : "24",
   "publication_title" : "Personeel en organisatie",
   "date_updated" : "2011-02-02 09:38:24",
   "publication_reference" : "Personeel en organisatie. 2010. Wolters Plantyn. 24 p.77-110",
   "departments" : "PP06",
   "publication_status" : "published",
   "people" : "Rots, Isabel (801001285713@PP06)",
   "publication_year" : "2010",
   "ugent_publication" : "UGENT",
   "title" : "Waarom stappen afgestudeerden aan de lerarenopleiding (niet) in het lerarenberoep? Een studie naar de rol van de lerarenopleiding",
   "type" : "bookChapter",
   "classification" : "B2"
},
{
   "creator" : "N/A",
   "subjects" : "Biology and Life Sciences",
   "pages_end" : "194",
   "publisher_place" : "Amsterdam, The Netherlands",
   "keywords" : "PATHWAYS ; COMT ; METHYLATION ; CAD ; CINNAMYL ALCOHOL-DEHYDROGENASE ; XYLEM ; CCoAOMT ; O-METHYLTRANSFERASE ACTIVITY ; lignin ; poplar ; Kraft pulping",
   "oldId" : "115038",
   "pages_start" : "187",
   "isbn" : "9780444509581",
   "id" : "402817",
   "publisher" : "Elsevier Science",
   "doi" : "http://hdl.handle.net/10.1016/S0921-0423(01)80072-1",
   "authors" : "Boerjan, Wout ; Meyermans, Hugo ; Chen, Cuiying ; Baucher, Marie ; Van Doorsselaere, Jan ; Morreel, Kris ; Messens, Eric ; Lapierre, Catherine ; Pollet, Brigitte ; Jouanin, Lise ; Leplé, Jean-Charles ; Ralph, John ; Marita, Jane ; Guiney, Emma ; Schuch, Wolfgang ; Petit-Conil, Michel ; Pilate, Gilles",
   "has_full_text" : "Y",
   "conference_date" : "2001-03-14",
   "isi_type" : "Article",
   "people" : "Boerjan, Wout (801000651674@WE09) ; Meyermans, Hugo (801000951768@onbekend) ; Chen, Cuiying (801001303392@WE14) ; Baucher, Marie (801000900036@onbekend) ; Van Doorsselaere, Jan (801000905490@onbekend) ; Morreel, Kris (801001178407@WE09) ; Messens, Eric (801000164048@WE09)",
   "publication_abbreviation" : "Progr. Biotechnol.",
   "ugent_publication" : "UGENT",
   "title" : "Lignin biosynthesis in poplar : genetic engineering and effects on kraft pulping",
   "type" : "conference",
   "classification" : "P1",
   "date_created" : "2008-05-14 16:22",
   "issn" : "0921-0423",
   "open_access" : "ugent",
   "conference_date_end" : "2001-03-17",
   "conference_name" : "International Wood Biotechnology Symposium (IWBS)",
   "issue_title" : "Molecular breeding of woody plants",
   "isi_id" : "ISIP:000178710200023",
   "volume" : "18",
   "language" : "eng",
   "publication_title" : "Progress in Biotechnology",
   "conference_location" : "Narita, Japan",
   "date_updated" : "2011-02-02 10:13:39",
   "publication_reference" : "Progr. Biotechnol. 2001. Elsevier Science. 18 p.187-194",
   "departments" : "WE09",
   "publication_status" : "published",
   "abstracts" : "Transgenic poplar, downregulated in cinnamyl alcohol dehydrogenase (CAD) or caffeic acid-O-methyltransferase (COMT) expression have been grown in field trials. Wood of these trees has been evaluated for Kraft pulping. The results show that lignin is more easily extracted from wood of the CAD-downregulated trees, whereas wood from COMT-downregulated trees is less suitable for Kraft pulping. Detailed NMR analyses of lignin from COMT-downregulated poplars reveal the presence of benzodioxane structures, which are derived from coupling of 5-hydroxyconiferyl alcohol with the lignin polymer, showing that monolignols other than p-coumaryl, coniferyl and sinapyl alcohol can be incorporated into lignin. Analysis of poplar downregulated for CCoAOMT shows that CCoAOMT is involved in the synthesis of both syringyl and guaiacyl units, and that sinapic is probably not an important precursor for syringyl lignin synthesis.",
   "sourceDb" : "aleph:pug01",
   "publication_year" : "2001"
},
{
   "creator" : "N/A",
   "subjects" : "Science General",
   "pages_end" : "70",
   "date_created" : "2004-05-24 13:27",
   "oldId" : "46141",
   "pages_start" : "1",
   "id" : "242821",
   "doi" : "http://hdl.handle.net/1854/LU-242821",
   "authors" : "BUEKENHOUT, F ; Van Maldeghem, Hendrik",
   "has_full_text" : "N",
   "language" : "eng",
   "publication_title" : "Mitt. Mathem. Sem. Giessen, 218",
   "date_updated" : "2009-06-09 15:32:13",
   "publication_reference" : "Mitt. Mathem. Sem. Giessen, 218. 1994. p.1-70",
   "departments" : "WE01",
   "publication_status" : "published",
   "people" : "Van Maldeghem, Hendrik (801000539116@WE01)",
   "sourceDb" : "aleph:pug01",
   "publication_year" : "1994",
   "ugent_publication" : "UGENT",
   "classification" : "U",
   "title" : "A Characterization of some Rank 2 Incidence Geometries by their Automorphism Group",
   "type" : "misc",
   "pages" : "1-70"
},
{
   "misc_type" : "bookReview",
   "creator" : "nrobbere",
   "subjects" : "Social Sciences",
   "pages_end" : "558",
   "date_created" : "2011-02-02 09:42:26",
   "issn" : "1048-6682",
   "open_access" : "ugent",
   "issue" : "4",
   "pages_start" : "549",
   "id" : "1114550",
   "doi" : "http://hdl.handle.net/10.1002/nml.236",
   "authors" : "Handy, Femida ; Hustinx, Lesley",
   "has_full_text" : "Y",
   "language" : "eng",
   "volume" : "19",
   "publication_title" : "Nonprofit Management and Leadership",
   "date_updated" : "2011-02-10 14:06:11",
   "publication_reference" : "Nonprofit Management and Leadership. 2009. 19 (4) p.549-558",
   "departments" : "PS04",
   "publication_status" : "published",
   "abstracts" : "Review of: - Volunteers: A Social Profile, by Marc A. Musick and John Wilson. Bloomington: Indiana University Press, 2007. 680 pp. - The Decision to Volunteer: Why People Give Their Time and How You Can Engage Them, by Beth Gazley and Monica Dignam. Washington, D.C.: ASAE and the Center for Association Leadership, 2008. 144 pp. - Challenges in Volunteer Management, edited by Matthew Liao-Troth. Charlotte, N.C.: Information Age, 2008. 292 pp.",
   "people" : "Hustinx, Lesley (802000853939@PS04)",
   "publication_year" : "2009",
   "ugent_publication" : "NOUGENT",
   "title" : "The why and how of volunteering",
   "type" : "misc",
   "classification" : "V"
},
{
   "creator" : "nrobbere",
   "subjects" : "Social Sciences",
   "pages_end" : "226",
   "date_created" : "2011-02-02 09:47:43",
   "issn" : "1744-8689",
   "open_access" : "open access at 2010-07-03",
   "issue" : "3",
   "keywords" : "survey research ; triangulation ; methodological critique ; Participation ; conceptual developments",
   "article_type" : "original",
   "pages_start" : "209",
   "id" : "1114560",
   "doi" : "http://hdl.handle.net/10.1080/17448680903351693",
   "authors" : "Hustinx, Lesley ; Denk, Thomas",
   "has_full_text" : "Y",
   "language" : "eng",
   "volume" : "5",
   "publication_title" : "JOURNAL OF CIVIL SOCIETY",
   "date_updated" : "2011-02-11 00:30:28",
   "publication_reference" : "JOURNAL OF CIVIL SOCIETY. 2009. 5 (3) p.209-226",
   "departments" : "PS04",
   "publication_status" : "published",
   "abstracts" : "Research on citizen participation has been guided by two core issues: first, the observation of a widening repertory of modes of participation, and second, the argument that participation is not an undifferentiated phenomenon, but must be conceived as an inherently multidimensional reality. In this article, we argue that conventional participation research has focused too one-sidedly on quantitatively expanding the range of types of activities, while the complex dimensionality is not reflected in the measures used. We formulate a methodological critique by using the metaphor of the 'black box', which refers to the implicit and unquestioned assumption that distinct types of activities and associations represent homogeneous and consistent realities that do not warrant further analytical decomposition. Surveys of participation allocate individuals to different 'participation boxes' by means of a binary logic, leaving a void of what is actually happening inside the boxes. To conclude, we reflect upon the fundamental dilemmas the black box of participation raises for theory and research, and offer conceptual and methodological keys to unlock the participation box.",
   "people" : "Hustinx, Lesley (802000853939@PS04)",
   "publication_year" : "2009",
   "ugent_publication" : "NOUGENT",
   "title" : "The 'black box' problem in the study of participation",
   "type" : "journalArticle",
   "classification" : "A2"
},
{
   "creator" : "kvdwalle",
   "subjects" : "Biology and Life Sciences",
   "pages_end" : "45",
   "issue" : "1",
   "keywords" : "MICROSTRUCTURE ; PH ; WATER ACTIVITY ; TEMPERATURE ; structured media ; population heterogeneity ; bacterial colony ; ESCHERICHIA-COLI ; GROWTH ; BACTERIAL COLONIES",
   "pages_start" : "39",
   "id" : "807243",
   "doi" : "http://hdl.handle.net/10.1111/j.1472-765X.2009.02623.x",
   "authors" : "Theys, TE ; Geeraerd, AH ; Devlieghere, Frank ; Van Impe, JF",
   "has_full_text" : "Y",
   "isi_type" : "Article",
   "people" : "Devlieghere, Frank (801000909433@LA07)",
   "publication_abbreviation" : "Lett. Appl. Microbiol.",
   "ugent_publication" : "UGENT",
   "title" : "Extracting information on the evolution of living- and dead-cell fractions of Salmonella Typhimurium colonies in gelatin gels based on microscopic images and plate-count data",
   "type" : "journalArticle",
   "classification" : "A1",
   "pages" : "7",
   "date_created" : "2009-12-11 10:54:32",
   "issn" : "0266-8254",
   "open_access" : "ugent",
   "article_type" : "original",
   "isi_id" : "000266924300007",
   "volume" : "49",
   "language" : "eng",
   "publication_title" : "LETTERS IN APPLIED MICROBIOLOGY",
   "date_updated" : "2009-12-14 12:09:01",
   "publication_reference" : "Lett. Appl. Microbiol. 2009. 49 (1) p.39-45",
   "departments" : "LA07",
   "publication_status" : "published",
   "abstracts" : "Aims: The aim of this study was to extract information on cell number and colony volume dynamics of Salmonella Typhimurium colonies. Methods and Results: Both cell number and colony volume of Salmonella Typhimurium in gelatin were monitored during the exponential and the stationary phase with varying pH and water activity, by plate counts and microscopic image analysis respectively. The exponential growth rates of cell numbers and colony volumes were correlated. The exponential growth rate of cell numbers was estimated based on this correlation and a secondary model that describes the effect of pH and water activity on the growth rate of the colony volumes. During the stationary phase, the cell number was constant, while colony volume increased, thus indicating the formation of a dead fraction. Models were developed to describe the living and dead population. Conclusions: By comparing colony volumes and cell numbers, the formation of dead fraction can be noticed from the beginning of the stationary phase, which indicates that the stationary phase is a dynamic - including both cell death and cell growth - rather than a static phase. Significance and Impact of the Study: This study was the first to investigate the proportion of living and dead bacteria within a stationary colony quantitatively.",
   "publication_year" : "2009"
},
{
   "misc_type" : "editorialMaterial",
   "creator" : "mghysbre",
   "subjects" : "Medicine and Health Sciences",
   "pages_end" : "G2",
   "date_created" : "2011-01-20 12:35:25",
   "issn" : "0264-410X",
   "open_access" : "ugent",
   "issue" : "6",
   "other_identifiers" : "isi:type:Editorial Material",
   "pages_start" : "G1",
   "id" : "1105537",
   "doi" : "http://hdl.handle.net/10.1016/j.vaccine.2010.06.078",
   "authors" : "Annemans, Lieven",
   "isi_id" : "000285232100001",
   "has_full_text" : "Y",
   "language" : "eng",
   "volume" : "28",
   "publication_title" : "VACCINE",
   "date_updated" : "2011-02-02 09:48:18",
   "publication_reference" : "VACCINE. 2010. 28 (6) p.G1-G2",
   "departments" : "GE12",
   "publication_status" : "published",
   "people" : "Annemans, Lieven (801001508005@GE12)",
   "publication_year" : "2010",
   "ugent_publication" : "UGENT",
   "title" : "Progress in vaccines, progress in health economics",
   "type" : "misc",
   "classification" : "V",
   "pages" : "2"
},
{
   "creator" : "nrobbere",
   "subjects" : "Social Sciences",
   "pages_end" : "13",
   "date_created" : "2011-02-02 09:51:31",
   "issn" : "1942-728X",
   "issue" : "1",
   "article_type" : "original",
   "pages_start" : "3",
   "id" : "1114566",
   "doi" : "http://hdl.handle.net/1854/LU-1114566",
   "authors" : "Hustinx, Lesley ; Handy, Femida",
   "has_full_text" : "N",
   "language" : "eng",
   "volume" : "26",
   "publication_title" : "THE INTERNATIONAL JOURNAL OF VOLUNTEER ADMINISTRATION",
   "date_updated" : "2011-02-10 16:09:54",
   "publication_reference" : "IJOVA. 2009. 26 (1) p.3-13",
   "departments" : "PS04",
   "publication_status" : "published",
   "people" : "Hustinx, Lesley (802000853939@PS04)",
   "publication_year" : "2009",
   "publication_abbreviation" : "IJOVA",
   "ugent_publication" : "NOUGENT",
   "title" : "Are volunteers attracted by the part or by the whole? The case of the Belgian red cross",
   "type" : "journalArticle",
   "classification" : "A2"
},
{
   "creator" : "nrobbere",
   "subjects" : "Social Sciences",
   "publisher_place" : "Brussel",
   "date_created" : "2011-02-03 11:24:02",
   "open_access" : "ugent",
   "id" : "1123142",
   "isbn" : "9782509007575",
   "publisher" : "Politeia",
   "doi" : "http://hdl.handle.net/1854/LU-1123142",
   "has_full_text" : "Y",
   "language" : "dut",
   "date_updated" : "2011-02-28 14:29:07",
   "publication_reference" : "2010. Politeia.",
   "departments" : "PS04",
   "publication_status" : "published",
   "abstracts" : "De revival van het vrijwilligerswerk is al een aantal jaren een feit. Maar recent duiken nieuwe vormen van vrijwilligerswerk op: in het bedrijfsleven, aan de overheid (OCMW’s, arbeidsmarktbeleid, gezondheidssector), in onderwijsinstellingen en andere instituten. Bovendien staan niet alle vrijwilligersorganisaties open voor alle doelgroepen. Het vrijwilligersbestand in Vlaanderen heeft er ongetwijfeld baat bij als we werk maken van de inzet van jongeren (via maatschappelijke stages), van ouderen (via een gericht beleid) en van kansengroepen (via verschillende ondersteunende maatregelen, een uitgestippeld arbeidsmarktbeleid, initiatieven vanuit OCMW’s). Creëert de driehoeksverhouding tussen vrijwilligerswerk, activering en arbeidsmarkt vrijwilligers tegen wil en dank? Of hebben Chinese vrijwilligers alleen maar te winnen bij het activeringsdiscours? In deze publicatie worden de ontwikkelingen van ‘geleid’ vrijwilligerswerk bekeken vanuit verschillende invalshoeken: maatschappelijk, historisch, wetenschappelijk. Het resultaat is een uniek boek dat focust op het vrijwilligerswerk in volle ontwikkeling.",
   "people" : "Hustinx, Lesley (802000853939@PS04)",
   "publication_year" : "2010",
   "ugent_publication" : "UGENT",
   "title" : "Chinese vrijwilligers? Over de driehoeksverhouding tussen vrijwilligerswerk, activering en arbeidsmarkt",
   "editors" : "Hustinx, Lesley",
   "type" : "bookEditor",
   "classification" : "B3",
   "pages" : "230"
},
{
   "creator" : "N/A",
   "subjects" : "Law and Political Science",
   "pages_end" : "411",
   "date_created" : "2004-01-14 13:34",
   "issn" : "0772-778X",
   "oldId" : "865",
   "pages_start" : "405",
   "id" : "110933",
   "doi" : "http://hdl.handle.net/1854/LU-110933",
   "authors" : "Steennot, Reinhard",
   "has_full_text" : "N",
   "language" : "dut",
   "publication_title" : "BANK- EN FINANCIEWEZEN",
   "date_updated" : "2009-02-24 10:20:52",
   "publication_reference" : "Bank Financiewez. 1999. p.405-411",
   "departments" : "RE05",
   "publication_status" : "published",
   "people" : "Steennot, Reinhard (801001239940@RE05)",
   "sourceDb" : "aleph:pug01",
   "publication_year" : "1999",
   "publication_abbreviation" : "Bank Financiewez.",
   "ugent_publication" : "UGENT",
   "title" : "Isabel of de innovatie in de bancaire wereld.",
   "type" : "journalArticle",
   "classification" : "A3",
   "pages" : "405-411"
},
{
   "creator" : "ldekock",
   "subjects" : "Philosophy and Religion",
   "pages_end" : "265",
   "publisher_place" : "Antwerpen",
   "date_created" : "2011-01-31 12:26:57",
   "open_access" : "ugent",
   "pages_start" : "235",
   "isbn" : "9789034193988",
   "id" : "1112448",
   "publisher" : "Standaard Uitgeverij",
   "doi" : "http://hdl.handle.net/1854/LU-1112448",
   "authors" : "De Kock, Liesbet",
   "has_full_text" : "Y",
   "language" : "dut",
   "publication_title" : "Overgangsrituelen : een brug tussen het andere en het gelijke",
   "date_updated" : "2011-02-09 08:44:35",
   "publication_reference" : "Overgangsrituelen : een brug tussen het andere en het gelijke. 2010. Standaard Uitgeverij. p.235-265",
   "departments" : "LW01",
   "publication_status" : "published",
   "people" : "De Kock, Liesbet (002001309656@LW01)",
   "publication_year" : "2010",
   "ugent_publication" : "UGENT",
   "title" : "Overgangsrituelen : vrijzinnig humanisme en rituelen",
   "type" : "bookChapter",
   "classification" : "B2"
},
{
   "creator" : "cscholla",
   "date_created" : "2009-06-18 14:52:40",
   "conference_date_end" : "2007-08-09",
   "conference_name" : "8th International Symposium on adjuvants for agrochemicals ISAA2007",
   "id" : "704290",
   "doi" : "http://hdl.handle.net/1854/LU-704290",
   "authors" : "De Schampheleire, Mieke ; Cornelis, Wim ; Steurbaut, Walter ; Spanoghe, Pieter",
   "language" : "eng",
   "has_full_text" : "N",
   "publication_title" : "Proceedings of the 8th International Symposium on adjuvants for agrochemicals ISAA2007",
   "conference_location" : "Columbus, Ohio (USA)",
   "date_updated" : "2009-11-05 11:21:35",
   "conference_date" : "2007-08-06",
   "publication_reference" : "Proceedings of the 8th International Symposium on adjuvants for agrochemicals ISAA2007. 2007.",
   "departments" : "LA03 ; LA12",
   "publication_status" : "published",
   "people" : "De Schampheleire, Mieke (801001754242@UGent) ; Cornelis, Wim (801000956418@LA12) ; Steurbaut, Walter (801000267314@LA03) ; Spanoghe, Pieter (801001266515@LA03)",
   "publication_year" : "2007",
   "ugent_publication" : "UGENT",
   "classification" : "C3",
   "title" : "Wind tunnel measurements to determine the efficiency of drift control agents",
   "type" : "conference"
},
{
   "creator" : "ldekock",
   "subjects" : "Philosophy and Religion",
   "pages_end" : "339",
   "publisher_place" : "Antwerpen",
   "date_created" : "2011-01-31 12:29:02",
   "open_access" : "ugent",
   "pages_start" : "308",
   "isbn" : "9789034193988",
   "id" : "1112464",
   "publisher" : "Standaard Uitgeverij",
   "doi" : "http://hdl.handle.net/1854/LU-1112464",
   "authors" : "De Kock, Liesbet",
   "has_full_text" : "Y",
   "language" : "dut",
   "publication_title" : "Overgangsrituelen : een brug tussen het andere en het gelijke",
   "date_updated" : "2011-02-09 08:31:22",
   "publication_reference" : "Overgangsrituelen : een brug tussen het andere en het gelijke. 2010. Standaard Uitgeverij. p.308-339",
   "departments" : "LW01",
   "publication_status" : "published",
   "people" : "De Kock, Liesbet (002001309656@LW01)",
   "publication_year" : "2010",
   "ugent_publication" : "UGENT",
   "title" : "Overgangsrituelen bij de Betamaribe",
   "type" : "bookChapter",
   "classification" : "B2"
},
{
   "misc_type" : "bookReview",
   "creator" : "cstalpae",
   "subjects" : "Arts and Architecture",
   "pages_end" : "81",
   "date_created" : "2011-01-11 09:54:14",
   "issn" : "0307-8833 ",
   "open_access" : "ugent at 2012-06-01",
   "issue" : "1",
   "keywords" : "spectatorship ; theatre ; tragedy ; genre",
   "pages_start" : "81",
   "id" : "1096806",
   "doi" : "http://hdl.handle.net/10.1017/S0307883310000751",
   "authors" : "Stalpaert, Christel",
   "has_full_text" : "Y",
   "language" : "eng",
   "volume" : "36",
   "publication_title" : "THEATRE RESEARCH INTERNATIONAL",
   "date_updated" : "2011-01-13 13:51:39",
   "publication_reference" : "Theatre res. int. 2011. 36 (1) p.81-81",
   "departments" : "LW17",
   "publication_status" : "published",
   "people" : "Stalpaert, Christel (801001014012@LW17)",
   "publication_year" : "2011",
   "publication_abbreviation" : "Theatre res. int.",
   "ugent_publication" : "UGENT",
   "title" : "To watch theatre : essays on genre and corporeality. By Rachel Fensham",
   "type" : "misc",
   "classification" : "V"
},
{
   "creator" : "avolkaer",
   "subjects" : "Medicine and Health Sciences",
   "pages_end" : "12",
   "date_created" : "2011-02-01 15:10:26",
   "issn" : "1781-5614 ",
   "open_access" : "ugent",
   "article_type" : "original",
   "pages_start" : "7",
   "id" : "1114029",
   "doi" : "http://hdl.handle.net/1854/LU-1114029",
   "authors" : "Labarque, Valery ; Cardon, Greet ; Van Cauwenberghe, Eveline ; Smits, Dirk",
   "has_full_text" : "Y",
   "language" : "dut",
   "publication_title" : "TIJDSCHRIFT VOOR LICHAMELIJKE OPVOEDING",
   "date_updated" : "2011-02-08 10:38:40",
   "publication_reference" : "Tijdschr. Licham. Opvoeding. 2010. p.7-12",
   "departments" : "GE25",
   "publication_status" : "published",
   "people" : "Labarque, Valery (801002113243@GE25) ; Cardon, Greet (801000968138@GE25) ; Van Cauwenberghe, Eveline (802000213638@GE25)",
   "publication_year" : "2010",
   "publication_abbreviation" : "Tijdschr. Licham. Opvoeding",
   "ugent_publication" : "UGENT",
   "title" : "Actieve lessen bewegingsopvoeding zijn belangrijk voor kleuters!",
   "type" : "journalArticle",
   "classification" : "A4"
},
{
   "creator" : "pbonte",
   "subjects" : "Philosophy and Religion",
   "pages_end" : "35",
   "publisher_place" : "Ghent",
   "date_created" : "2010-10-04 11:28:28",
   "issn" : " 1373-0975",
   "open_access" : "open access",
   "issue" : "2",
   "keywords" : "Verbeterkunde Enhancement medicine Transhumanisme Transhumanism Eugenetica Eugenics Biotechnologie Biotechnology Bio-ethiek Bioethics Vrijheid Zelfbeschikkingsrecht",
   "article_type" : "original",
   "pages_start" : "18",
   "id" : "1048706",
   "publisher" : "Academia Press",
   "doi" : "http://hdl.handle.net/1854/LU-1048706",
   "authors" : "Bonte, Pieter",
   "has_full_text" : "Y",
   "language" : "dut",
   "publication_title" : "Ethiek & Maatschappij",
   "date_updated" : "2011-02-10 14:20:48",
   "publication_reference" : "Ethiek & Maatschappij. 2008. Academia Press. (2) p.18-35",
   "departments" : "LW01",
   "publication_status" : "published",
   "abstracts" : "As the reach of medical technology continues to expand, not only the goal of healing is being reached but beyond that the enhancement of the human body and mind also becomes a reality. Examples can be found in advanced prostheses, neurofarmaceuticals, genetic technologies and other fields. The ethical value of this enhancement medicine is being debated fiercly. Often the debate takes the form of a so-called ‘bio-conservative’ stance as opposed to a ‘transhumanist’ position. Transhumanists argue for the fundamental right to ‘morphological freedom’: every individual has, in principle, the right to determine for himself the shape and functions of his own body and every intrusion on this fundamental right – the blanket prohibition on any kind of enhancement medicine being the prime example hereof – has to be accompanied by strong ethical or societal arguments. Bioconservatives often argue precisely for such a general and universal prohibition, often based on intrinsic ethical arguments concerning the goodness of human nature and the unacceptability to freely alter this nature, even if such a choice is based on the sincere personal wish of an informed and socially responsible individual. I focus on these intrinsic arguments concerning the goodness of enhancement. I analyse the bioconservative arguments to conclude that they are incoherent and sometimes even internally inconsistent. Blindness for the responsibility of non-intervention plays a key role here. Furthermore I argue that the fundamental right to morphological freedom should logically be protected in any liberal democratic ethical theory. None the less, as the biological mold of human nature becomes a field of our own cultural agency, our natural passions dissolve as a source of spontaneous motivation. Thus the reality of ever-deepening morphological freedom confronts us with a new existential shock which has not yet been brought into clear focus and which poses a profound challenge for much of modern day discourse on motivation and choice.",
   "people" : "Bonte, Pieter (002002311887@LW01)",
   "publication_year" : "2008",
   "ugent_publication" : "NOUGENT",
   "title" : "De verbeterkunde, een ongewenste bevrijding?",
   "type" : "journalArticle",
   "classification" : "A2"
},
{
   "additionalInformation" : "abstract no. 1493",
   "creator" : "augurlu",
   "subjects" : "Technology and Engineering",
   "pages_end" : "299",
   "issue" : "2",
   "pages_start" : "299",
   "id" : "732249",
   "publisher" : "Society of Nuclear Medicine",
   "doi" : "http://hdl.handle.net/1854/LU-732249",
   "authors" : "Clementel, Enrico ; Van Elmbt, L ; Guerchaft, M ; Bol, A ; Staelens, Steven ; Vandenberghe, Stefaan",
   "has_full_text" : "N",
   "conference_date" : "2009-06-13",
   "people" : "Clementel, Enrico (802000402786@TW06) ; Staelens, Steven (801001554582@TW06) ; Vandenberghe, Stefaan (801001340071@TW06)",
   "publication_abbreviation" : "J. Nucl. Med.",
   "ugent_publication" : "UGENT",
   "title" : "Impact of time-of-flight on quantitative accuracy and volume determination in non-uniform phantoms",
   "type" : "conference",
   "classification" : "C3",
   "date_created" : "2009-08-21 12:13:48",
   "issn" : "0161-5505",
   "conference_date_end" : "2009-06-17",
   "conference_name" : "SNM 56th Annual Meeting",
   "issue_title" : "2009 SNM Annual Meeting Scientific Abstracts",
   "volume" : "50",
   "language" : "eng",
   "publication_title" : "JOURNAL OF NUCLEAR MEDICINE",
   "conference_location" : "Toronto, Canada",
   "date_updated" : "2009-11-05 11:22:15",
   "publication_reference" : "J. Nucl. Med. 2009. Society of Nuclear Medicine. 50 (2) p.299-299",
   "departments" : "TW06",
   "publication_status" : "published",
   "publication_year" : "2009"
},
{
   "creator" : "mghysbre",
   "subjects" : "Medicine and Health Sciences",
   "pages_end" : "4046",
   "date_created" : "2011-01-20 12:35:25",
   "issn" : "0066-4804",
   "open_access" : "ugent",
   "issue" : "9",
   "keywords" : "NOSOCOMIAL INFECTION ; BLOOD-STREAM INFECTION",
   "article_type" : "letterNote",
   "pages_start" : "4046",
   "id" : "1105564",
   "doi" : "http://hdl.handle.net/10.1128/AAC.00689-10",
   "authors" : "Blot, Stijn ; VANDIJCK, DOMINIQUE ; Lizy, Christelle ; Annemans, Lieven ; Vogelaers, Dirk ; Mauldin, Patrick D ; Salgado, Cassandra D ; Bosso, John A",
   "isi_id" : "000281005900085",
   "has_full_text" : "Y",
   "language" : "eng",
   "volume" : "54",
   "publication_title" : "ANTIMICROBIAL AGENTS AND CHEMOTHERAPY",
   "date_updated" : "2011-02-02 10:17:36",
   "publication_reference" : "Antimicrob. Agents Chemother. 2010. 54 (9) p.4046-4046",
   "isi_type" : "Letter",
   "departments" : "GE12",
   "publication_status" : "published",
   "people" : "Blot, Stijn (801001556606@GE01) ; VANDIJCK, DOMINIQUE (002000631666@UGent) ; Lizy, Christelle (000080773718@UGent) ; Annemans, Lieven (801001508005@GE12) ; Vogelaers, Dirk (801000461314@GE01)",
   "publication_year" : "2010",
   "publication_abbreviation" : "Antimicrob. Agents Chemother.",
   "ugent_publication" : "UGENT",
   "title" : "Estimating the length of hospitalization attributable to multidrug antibiotic resistance",
   "type" : "journalArticle",
   "classification" : "A1"
},
{
   "creator" : "evbraeck",
   "subjects" : "Medicine and Health Sciences",
   "pages_end" : "523",
   "date_created" : "2011-02-02 09:57:58",
   "issn" : "1058-4838",
   "open_access" : "open access",
   "issue" : "4",
   "keywords" : "vaccine ; HIV",
   "other_identifiers" : "isi:id:to be confirmed;isi:type:to be confirmed",
   "article_type" : "original",
   "pages_start" : "522",
   "id" : "1114576",
   "doi" : "http://hdl.handle.net/10.1093/cid/ciq160",
   "authors" : "Van Braeckel, Eva ; Bourguignon, Patricia ; Koutsoukos, Marguerite ; Clement, Frédéric ; Janssens, Michel ; Carletti, Isabelle ; Collard, Alix ; Demoitié, Marie-Ange ; Voss, Gerald ; Leroux-Roels, Geert ; McNally, Lisa",
   "has_full_text" : "Y",
   "language" : "eng",
   "volume" : "52",
   "publication_title" : "CLINICAL INFECTIOUS DISEASES",
   "date_updated" : "2011-02-03 13:34:13",
   "publication_reference" : "Clin. Infect. Dis. 2011. 52 (4) p.522-523",
   "departments" : "GE06",
   "publication_status" : "published",
   "abstracts" : "Background. This phase I/II partially blinded, randomized, dose-ranging study assessed the safety and immunogenicity of a novel human immunodeficiency virus type 1 (HIV-1) vaccine candidate consisting of a recombinant fusion protein (F4) containing 4 HIV-1 clade B antigens (Gag p24, Pol reverse transcriptase, Nef, and Gag p17) adjuvanted with AS01 in HIV-seronegative volunteers. Methods. Two doses of the recombinant F4 protein (10, 30, or 90 μg/dose), adjuvanted with AS01 or reconstituted with water for injection, were administered 1 month apart to 180 healthy volunteers aged 18-40 years. F4-specific CD4(+) T cell responses were measured using intracellular cytokine staining after in vitro stimulation by overlapping peptide pools covering the 4 individual antigens. Results. Reactogenicity was higher during the 7-day period after each vaccine dose in the adjuvanted than in the nonadjuvanted groups. In the adjuvanted groups, the overall immune response rate was high after the second vaccine dose, with highest responder rates seen in the 10-μg F4/AS01 group (100% to 3 HIV-1 antigens and 80% to all 4 HIV-1 antigens). High and long-lasting CD4(+) T cell frequencies were observed (up to a median value of 1.2% F4-specific CD4(+) T cells at day 44), with strongest responses directed against reverse transcriptase. Antigen-specific CD4(+) T cells exhibited a polyfunctional phenotype, expressing at least CD40 ligand and interleukin 2, often in combination with tumor necrosis factor α and/or interferon γ. Vaccine-induced CD4(+) T cell responses were broadly cross-reactive to all 4 antigens derived from HIV-1 clades A and C. Conclusions. These results support further clinical investigation of this HIV-1 vaccine candidate both in a prophylactic setting (alone, in conjunction with an envelope-based antigen or in combination with other vaccine approaches in a heterologous prime-boost regimen) and as a potentially disease-modifying therapeutic vaccine in HIV-1-infected subjects.",
   "people" : "Van Braeckel, Eva (802000044391@CA80) ; Clement, Frédéric (801001012493@GE06) ; Leroux-Roels, Geert (801000485057@GE06)",
   "publication_year" : "2011",
   "publication_abbreviation" : "Clin. Infect. Dis.",
   "ugent_publication" : "UGENT",
   "title" : "An adjuvanted polyprotein HIV-1 vaccine induces polyfunctional cross-reactive CD4+ T cell responses in seronegative volunteers",
   "type" : "journalArticle",
   "classification" : "A1"
},
{
   "creator" : "smladeno",
   "subjects" : "Technology and Engineering",
   "pages_end" : "46",
   "publisher_place" : "Campbell, CA, USA",
   "keywords" : "OLED ; exciton decay time",
   "pages_start" : "43",
   "id" : "772406",
   "publisher" : "Society for Information Display (SID)",
   "doi" : "http://hdl.handle.net/1854/LU-772406",
   "authors" : "Mladenovski, Saso ; Reineke, Sebastian ; Neyts, Kristiaan",
   "has_full_text" : "Y",
   "conference_date" : "2009-09-14",
   "people" : "Mladenovski, Saso (802000086528@UGent) ; Neyts, Kristiaan (801000630557@TW06)",
   "publication_abbreviation" : "Conf. Rec. Int. Disp. Res. Conf.",
   "ugent_publication" : "UGENT",
   "title" : "Modeling exciton decay time and radiative efficiency in organic light emitting devices",
   "type" : "conference",
   "classification" : "P1",
   "date_created" : "2009-11-05 11:00:47",
   "issn" : "1083-1312",
   "conference_date_end" : "2009-09-17",
   "open_access" : "ugent",
   "other_identifiers" : "isi:type:Proceedings Paper",
   "conference_name" : "29th International Display Research Conference (IDRC 2009 / Eurodisplay 2009)",
   "issue_title" : "Eurodisplay 2009 : proceedings of the 29th International Display Research Conference",
   "isi_id" : "000281650300007",
   "language" : "eng",
   "publication_title" : "CONFERENCE RECORD OF THE INTERNATIONAL DISPLAY RESEARCH CONFERENCE",
   "conference_location" : "Rome, Italy",
   "date_updated" : "2010-10-06 14:35:31",
   "publication_reference" : "Conf. Rec. Int. Disp. Res. Conf. 2009. Society for Information Display (SID). p.43-46",
   "departments" : "TW06",
   "publication_status" : "published",
   "abstracts" : "The exciton decay time depends on the optical environment in which the decay takes place. In the case of an organic light-emitting device this environment is determined by the thin film layer structure. The radiative and non-radiative decay channels compete and in this way influence the radiative efficiency and the external quantum efficiency of the device. This paper shows an experimentally verified model to estimate the dependency of the exciton decay time and the radiative efficiency on the thin film stack.",
   "publication_year" : "2009"
}
]
